config/routes.rb
Rails.application.routes.draw do
  
  
  resources :profiles, as: :users, only: [:show, :update]
  
  #devise_for :users, controllers: {registrations: "registrations"}
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  #Redireccionar c a companies
  get '/c/:id', to: redirect('/companies/%{id}')
  
  resources :companies do
  	resources :cards do
      resources :transactions
    end
    #Entorno de trabajo
    get 'panel', to: 'cards#scan'
    post 'panel', to: 'cards#scan'
    get 'prueba', to: 'companies#freeTrial'
    get 'stats', to: 'companies#stats'
    get 'requestCard', to: 'companies#send_mail_card_request'
  
  end

  #Ruta para asignar usuario a tarjeta existente
  post 'asignar', to: 'cards#asignuser'
  

  #Mostrar INDEX si está logueado
  authenticated :user do
  	root 'main#index'
  end
  
  #Mostrar página de aterrizaje si no está logueado
  unauthenticated :user do
  	devise_scope :user do
  		root 'main#landing'
  	end
  end

  #Rutas dinámicas para nombres de usuario de las compañías
  #datos = Company.all
  
  #datos.each do |c|
    #A menos que el alias esté vacío...
  #  unless c.alias == nil
  #    get c.alias, to: 'companies#show', :id => c.id    
  #  end
  #end
  

end

app/models/company.rb
class Company < ApplicationRecord
	has_attached_file :cover, styles: { large: "1280x720>" , medium: "300x150", thumb: "100x100>" }, default_url: "/images/:style/missing_cover.jpg"
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
	has_many :cards

	has_attached_file :logo, styles: { large: "1280x720>" , medium: "300x150", thumb: "100x100>" }, default_url: "/images/:style/missing_logo.jpg"
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

	has_attached_file :picture, styles: { large: "1280x720>" , medium: "300x150", thumb: "100x100>" }, default_url: "/images/:style/missing_picture.jpg"
	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  #Admin sin restricciones
  before_action :authenticate_admin!, only: [:index, :destroy]
  #Dueño de compañía A, SHOW y EDIT compañía A.
  before_action :authenticate_owner!, only: [:edit, :update, :stats]
  #Empleado de compañía A, SHOW de compañía A.
  #Cliente, NADA.

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @npa = "false"
    if user_signed_in?
      verify_own_id_npa
      @cards = Card.where(company_id: @company.id, user: current_user.id)
    end

    render layout: "companies"
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    verify_own_id
  end
  def freeTrial

    set_company_id
    if @company.clientcount == 0
      buenas=0
      malas=0
      for i in 1..10
        card = Card.new
        card.company_id = @company.id
        card.credit1 = 0
        card.credit2 = 0
        card.credit2_enabled = true
      # Armar CLIENT(i) y NUMBER (CO,CO,CO,CO,CL,CL,CL,CL,CL)
        card.client = i
        #Llevar CLIENT a 5 caracteres
        cl=i.to_s

        unless cl.length==5
            begin
                cl="0"+cl
            end until cl.length==5
        end

        #Llevar COMPANY a 4 caracteres
        co=@company.id.to_s

        unless co.length==4
            begin
                co="0"+co
            end until co.length==4
        end

        card.number=co+cl
      # Generar PIN aleatorio
        card.pin = rand(1000..9999)

        #Cambiar STATUS según opción elegida

        # Si se guarda, avisar, si no ... también

          if card.save
            buenas=buenas+1
            @company.clientcount=@company.clientcount+1
            @company.save
          else
            malas=malas+1
          end
        end       
        redirect_to company_prueba_path(@company), notice: "Se crearon tus 10 tarjetas de prueba... 
        Tarjetas exitosas: " + buenas.to_s + " | Tarjetas malas: " + malas.to_s + " | Empezando desde el ID: 1 hasta : 10"

    end
    unless @company.alias == "freeTrial"
      redirect_to root_path
    end
  end
  # POST /companies
  # POST /companies.json
  def create
    
    @company = Company.new(company_params)
    #Si el usuario tiene permiso 32, decirle que afloje un toque...
    if current_user.permissions == 32
      redirect_to root_path
    else
    #Si el usuario no es administrador, entonces solicitó una prueba gratuita.
    #forzar los parámetros estándar de la prueba gratuita
    unless current_user.is_admin?
      @company.admin = current_user.id
      @company.clientcount = 0
      @company.alias = "freeTrial"
      #Bloquear la creación de empresas (para que no cree 2 millones...)
      #usando el permiso 32
      if current_user.permissions < 30
        current_user.permissions = 32
        current_user.save
      end
    end
    
    

      respond_to do |format|
        if @company.save
          format.html { redirect_to company_prueba_path(@company) }
          format.json { render :show, status: :created, location: @company }
        else
          format.html { render :new }
          format.json { render json: @company.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Se actualizaron los datos correctamente.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def stats
    set_company_id
    verify_own_id

    #Consultar a la base de datos
    @allTransactions = Transaction.where('company_id' => @company.id)
    @allCards = Card.where('company_id' => @company.id)

    @counter = Array.new
    #Contar transacciones realizadas
    @counter[1] = @allTransactions.count
    
    #Contar tarjetas totales
    @counter[2] = @allCards.count

    #Contar tarjetas activas
    @counter[3] = @allCards.where('status'=> 1).count

    #Tarjetas inactivas
    @counter[4] = @allCards.where('status'=> 0).count

    #Tarjetas robadas
    @counter[5] = @allCards.where('status'=> 2).count

    #Tarjetas registradas
    @counter[6] = @allCards.where.not('user'=>nil).count

    #Tarjetas NO registradas
    @counter[7] = @allCards.where('user'=>nil).count

    #Iterar transactions
      #Total de saldo ingresado
      
      #Total de saldo consumido

      #Total de puntos ingresados

      #Total de puntos consumidos

    #Iterar CARDS
      #find Cliente. Guardarlo en array.

        #Sumar credit1

        #Sumar credit2
      #Si no es cliente registrado, guardarlo en otro array.
        
        #Sumar credit1

        #Sumar credit2
    
  end

  def send_mail_card_request
    set_company_id
    ClientToOwnersMailer.with(user: current_user, company: @company).new_card_request.deliver_now
    
    redirect_to company_path(@company.id, notice: "Listo! Ya enviamos tus datos al administrador de #{@company.name}, para que cree tu tarjeta. Se pondrá en contacto con vos a la brevedad.")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end
    def set_company_id
      @company = Company.find(params[:company_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :url, :admin, :clientcount, :employers, :alias, :cover, :markdown_content, :facebook, :website, :twitter, :email, :instagram, :linkedin, :whatsapp, :phone, :store_enabled, :picture, :logo, :about_us_enabled, :other_info_enabled, :about_us, :other_info)
    end

    def verify_own_id_npa
      unless (@company.admin == current_user.id) or current_user.is_admin?

           @npa = "true"
    
      end

    end
    def verify_own_id
      unless (@company.admin == current_user.id) or current_user.is_admin?

           redirect_to root_path
    
      end

    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
	
end

app/views/companies/Ashow.haml
:javascript
  $(document).ready(function(){
    $('ul.tabs').tabs();
    swipeable : true,
    responsiveThreshold : 150
    $('.collapsible').collapsible();
    function Foco(){
      document.getElementById('input#clientnum').focus();
      alert("funca");
    }
    setInterval(Foco,1000);
  });





.container
  .row
    %p{:id=>"notice" }
  .row
    .col.s12
      %ul{:id=>"tabs-swipe-demo", :class=>"tabs"}
        %li{:class=>"tab col s3"}
          %a{:href=>"#tab-1", :class=>"active"}Créditos/Débitos
        %li{:class=>"tab col s3"}
          %a{:href=>"#informes"}Alta de tarjeta
        %li{:class=>"tab col s3"}
          %a{:href=>"#clientes"}Clientes
      %div{:id=>"tab-1", :class=>"col s12 green lighten-3"}
      =form_for :cards, url: {action: "update"} do |f|
        %ul{:class=>'collapsible', :data-collapsible=>'accordion'}
          %li
            .collapsible-header
              %i.material-icons filter_drama
              Escanear código de barras
            .collapsible-body
              .row.center
                
                .input-field.col.s9
                  %i{:class=>"material-icons prefix"} credit_card
                  = label_tag(:icon_prefix, "Código de barras", :class=>"icon_prefix")
                  = text_field_tag(:icon_prefix,"", class: "validate")
                .col.s3
                  = submit_tag("Buscar",:class=>"waves-effect waves-light btn")
        %ul{:class=>'collapsible', :data-collapsible=>'accordion'}
          %li
            .collapsible-header.active
              %i.material-icons filter_drama
              Introducir datos manualmente
            .collapsible-body.white
              .row
                .input-field
                  Código de país: 779 [ARGENTINA]
                .input-field
                  Empresa:
                  = @company.id
                  [
                  =@company.name
                  ]
                .input-field
                  = label_tag(:clientnum, "Número de cliente", :class=>"icon_prefix")
                  = text_field_tag(:clientnum,"", class: "validate")
                  %p1
        .input-field
          = submit_tag("Buscar",:class=>"waves-effect waves-light btn")

      %div{:id=>"informes", :class=>"col s12 blue lighten-4"}
        .row.center
        .row.center
          =form_tag do
            .row.center
              .input-field.col.s9
                %i{:class=>"material-icons prefix"} credit_card
                = label_tag(:icon_prefix, "Escanear código o escribir número de tarjeta", :class=>"icon_prefix")
                = text_field_tag(:icon_prefix,"", class: "validate")
              .col.s3
                -# =link_to 'Dar de alta', new_company_client_path(@company),:class=>"waves-effect waves-light btn"
      %div{:id=>"clientes", :class=>"col s12 blue lighten-5"}
        %p Listado de clientes




-# Comparar si = @company.admin = usuarioactual, y mostrar opciones de administración
-# = link_to 'Edit', edit_company_path(@company)
-# = link_to 'Atrás', companies_path
-# Comparar si alguno de los = @company.employers = usuarioactual, y mostrar opciones de administración para empleados

app/views/companies/_company_menu.haml
#dropMenu.modal.bottom-sheet
  .col.s12.center
    %h1 Gestión de empresa
    -if @company.alias == "freeTrial"
      =link_to "Instrucciones de prueba", company_prueba_path(@company)
  %ul.collapsible{"data-collapsible"=>"accordion"}
    %li
      .collapsible-header
        %i.material-icons touch_app
        Entorno móvil
      .collapsible-body
        %span Es el entorno que permitirá realizar créditos y débitos usando la cámara de un dispositivo móvil para la lectura del código de barras.
        %p
        =link_to "Ir", company_panel_path(@company, :mobile => true), :class=> "btn"
    %li
      .collapsible-header
        %i.material-icons important_devices
        Entorno general
      .collapsible-body
        %span Es la forma más eficiente de realizar créditos y débitos a tarjetas de clientes. Está diseñado para una rápida carga con lector de códigos de barra o bien para un ingreso manual del número de cliente.
        %p
        =link_to "Ir", company_panel_path(@company), :class=> "btn"
    %li
      .collapsible-header
        %i.material-icons
          credit_card
        Crear tarjetas
      .collapsible-body
        %span Desde este menú se podrán dar de alta tarjetas de membresía para luego:
        %ul
          %li encargar su impresión,
          %li imprimir tarjetas de códigos con diseño estándar, o bien 
          %li imprimir lista de códigos de barra y PIN para encargar la producción de las tarjetas a #{@company.name}
        %p
          =link_to "Ir", new_company_card_path(@company), :class=> "btn"
    %li
      .collapsible-header
        %i.material-icons people
        Clientes
      .collapsible-body
        %span Desde aquí se pueden visualizar todas las tarjetas dadas de alta y toda la información relativa a las mismas, incluyendo los datos de los usuarios que las han registrado.
        %p
          =link_to "Ir", company_cards_path(@company), :class=> "btn"
    %li
      .collapsible-header
        %i.material-icons timeline
        Estadísticas
      .collapsible-body
        =link_to "Estadísticas", company_stats_path(@company)

app/views/companies/_form.html.erb
<div class="container">
  <div class="card">
<%= form_with(model: company, local: true, html: { multipart: true }) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :company_url %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.number_field :admin, id: :company_admin %>
  </div>

  <div class="field">
    <%= form.label :clientcount %>
    <%= form.number_field :clientcount, id: :company_clientcount %>
  </div>

  <div class="field">
    <%= form.label :employers %>
    <%= form.text_field :employers, id: :company_employers %>
  </div>

  <div class="field">
    <%= form.label :alias %>
    <%= form.text_field :alias, id: :company_alias %>
  </div>
  <div>Imagen actual
    <%= image_tag @company.cover.url(:medium) %>
  </div>
 <div class="field">
    Cambiar imagen
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div></div>

app/views/companies/_forma.html.erb
<div class="container">
  <div class="card">
<%= form_with(model: company, local: true, html: { multipart: true }) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :company_url %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.number_field :admin, id: :company_admin %>
  </div>

  <div class="field">
    <%= form.label :clientcount %>
    <%= form.number_field :clientcount, id: :company_clientcount %>
  </div>

  <div class="field">
    <%= form.label :employers %>
    <%= form.text_field :employers, id: :company_employers %>
  </div>

  <div class="field">
    <%= form.label :alias %>
    <%= form.text_field :alias, id: :company_alias %>
  </div>
  <div>Imagen actual
    <%= image_tag @company.cover.url(:medium) %>
  </div>
 <div class="field">
    Cambiar imagen
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div></div>

app/views/companies/edit.haml
- @tit = "Edición de página de comercio"

= render 'form', company: @company

= link_to 'Atrás', companies_path 

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Admin</th>
      <th>Clientcount</th>
      <th>Employers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.url %></td>
        <td><%= company.admin %></td>
        <td><%= company.clientcount %></td>
        <td><%= company.employers %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<% tit = "Nueva compañía" %>

<%= render 'form', company: @company %>

<%= link_to 'Volver', companies_path, :class=> "btn" %>

app/views/companies/show.haml
:javascript
  $(document).ready(function(){
    $('.parallax').parallax();
    $('.collapsible').collapsible();
    $('.carousel-slider').slider({full_width: true});//slider init
    $('.carousel').carousel();
    $(".button-collapse").sideNav();
    $('.scrollspy').scrollSpy();
    $('.modal').modal();
  });
  $( window ).load(function() {
    $('.parallax').parallax();
    $('.carousel').carousel();
    $(".button-collapse").sideNav();
    $('.carousel-slider').slider({full_width: true});//slider init
    $('.scrollspy').scrollSpy();
    $('.modal').modal();
  });
-if user_signed_in?
  -if @npa == "false"
    %nav.black.white-text.center-xs
      .nav-wrapper.center-xs
        %ul#nav-mobile
          %li
            =link_to "Editar página", edit_company_path(@company.id), :class => "btn red"
          %li
            %a.modal-trigger.btn.green{:href=>"#dropMenu", "data-activates"=>"dropMenu"}
              %span Menu
              %i.material-icons arrow_drop_down
    / MENÚ DE EMPRESA
    =render partial: "company_menu"
    %ul.modal.bottom-sheet.hide 
      -if @company.alias == "freeTrial"
        %li
          =link_to "Instrucciones de prueba", company_prueba_path(@company)
      %li
        =link_to "Panel con CÁMARA", company_panel_path(@company, :mobile => true)
      %li
        =link_to "Panel GENERAL", company_panel_path(@company)
      %li
        =link_to "Crear tarjetas", new_company_card_path(@company)
      %li
        =link_to "Clientes", company_cards_path(@company)
      %li
        =link_to "Estadísticas", company_stats_path(@company)

















%nav.white
  .nav-wrapper
    .brand-logo
      =image_tag(@company.logo.url(:medium), height: 50)
    .hide-on-large-only
      %a.black-text.button-collapse.sidenav-trigger{"data-activates"=>"mobile-demo", :href => "#"}
        %i.material-icons menu
    %ul.right.hide-on-med-and-down.black-text
      -if @company.about_us_enabled?
        %li
          %a.black-text{ :href => "#about"} Acerca de
      -if @company.other_info_enabled?
        %li
          %a.black-text{ :href => "#other"} Otra info
      %li
        %a.black-text{ :href => "#social"} Social
      -unless user_signed_in?
        %li
          %a.black-text{ :href => "#cards"} Ingresar
%ul.side-nav#mobile-demo
  %li.center
    =image_tag(@company.logo.url(:medium), :class => "logoCompany")
  -if @company.about_us_enabled?
    %li
      %a.black-text{ :href => "#about"} Acerca de
  -if @company.other_info_enabled?
    %li
      %a.black-text{ :href => "#other"} Otra info
  %li
    %a.black-text{ :href => "#social"} Social
  -unless user_signed_in?
    %li
      %a.black-text{ :href => "#cards"} Ingresar
  -if user_signed_in?
    %li
      %a.black-text{ :href => "#cards"} Tarjetas!
.parallax-container.valign-wrapper.center-xs
  .parallax
    =image_tag(@company.cover.url(:large), :alt => "Portada")
  %h1.titCompany.center-xs.middle-xs
    =image_tag(@company.logo.url(:medium), :class => "logoCompany")
    /= @company.name
-unless notice==nil
  .container
    .row.center          
      -if notice[0,2]=="**"
        .card.red
          %h1.white-text <i class="material-icons">error</i> Ocurrió un error

          %strong.white-text
            =notice
        #noticia.modal.modal-fixed-footer
          .modal-content
            %h4 Epa! Hubo un error
            %p
              =notice
          .modal-footer.center
            %a.modal-action.modal-close.waves-effect.btn-flat Cerrar
          %script
            noticia.open();
      -else
        -if notice[0,3]=="*T*"
        -else
          .chip.red.center-xs.center
            = notice
.container
  .row.valign-wrapper
    .col.s12.m4
      =image_tag(@company.picture.url(:large), :class => "pictureCompany")
    .col.s12.m8
      -markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
      -unless @company.markdown_content == nil
        =raw(markdown.render(@company.markdown_content).html_safe)
  
  
  -if @company.store_enabled?
    .col.s12
      .red.texto-blanco.center.bordeRedondeado Muy pronto vas a poder habilitar tu tienda, y se va a ver más o menos así!
      %h2 Tienda
      En nuestra tienda, podrás adquirir nuestros productos y servicios.
      .carousel
        %a.carousel-item{:href=>"#one!"}
          =image_tag("03")
        %a.carousel-item{:href=>"#two!"}
          =image_tag("2bg")
        %a.carousel-item{:href=>"#three!"}
          =image_tag("p3")
        %a.carousel-item{:href=>"#one!"}
          =image_tag("03")
        %a.carousel-item{:href=>"#two!"}
          =image_tag("2bg")
        %a.carousel-item{:href=>"#three!"}
          =image_tag("p3")
    .col.s12.center
      %a.btn.center.grey.darken-4
        %i.material-icons shopping_cart
        Entrar a la tienda
.container.middle-xs
  -if @company.about_us_enabled?
  
    .col.s12.m6
      .card.horizontal.grey.darken-3.white-text.littlePadding2
        -markdownAbUs = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
        -unless @company.about_us == nil or @company.about_us == "" or @company. == " "
          .section.scrollspy#about
            =raw(markdownAbUs.render(@company.about_us).html_safe)
  -if @company.other_info_enabled?  

    .col.s12.m6
      .card.horizontal.grey.darken-5.white-text.littlePadding2
        -markdownOtIn = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
        -unless @company.other_info == nil or @company.other_info == "" or @company. == " "
          .section.scrollspy#other
            =raw(markdownOtIn.render(@company.other_info).html_safe)
    
.container.middle-xs.littleMargin.center
  .col.s12.center.section.scrollspy#cards
    -if user_signed_in?
      
      %h2 Tus tarjetas de #{@company.name}
      -if @cards.count >0
        -@cards.each do |card|
          .col-xs-12.col-sm-6.col-md-4
            .card
              .card-image.waves-effect.waves-block.waves-light
                =image_tag(@company.cover.url(:medium), :alt => "Portada de #{@company.name}", :class=> "activator", :height => "150px", :width => "300px")
                /=image_tag(@company.logo.url(:thumb), :alt => "Logo de #{@company.name}", height: 30)
              .card-content
                %span.card-title.activator.grey-text.text-darken-4
                  = @company.name
                  .chip #{card.client.to_s}
                  %i.material-icons.right more_vert
                %p.center
                  Saldo: $
                  = (card.credit1.to_f)/100

                  | Puntos: 
                  = card.credit2
    
              .card-reveal
                %span.card-title.grey-text.text-darken-4
                  =@company.name
                  %i.material-icons.right close
                
                .collection
                  = link_to 'Movimientos', company_card_transactions_path(card.company,card.id), :class=>"collection-item"
                  = link_to 'Baja', company_card_transactions_path(card.company,card.id), :class=>"collection-item"
                  = link_to 'Configuración', company_card_transactions_path(card.company,card.id), :class=>"collection-item"
      -else
        No tenés tarjetas
        =render partial: "layouts/add_card"
        
      =link_to "Solicitar nueva tarjeta ", company_requestCard_path(@company.id)
    -else
      %p.texto-celeste.center Iniciá sesión o creá una nueva cuenta en Praemium, para obtener tu tarjeta de beneficios de este comercio.
      .col.s12.m6.center-xs.littleMargin
        =link_to "Crear cuenta", new_user_registration_path(redirect_to: request.path), :class=> "btn waves-effect grey darken-5 white-text"
      .col.s12.m6.center-xs.littleMargin  
        =link_to "Iniciar sesión", new_user_session_path(redirect_to: request.path), :class=> "btn waves-effect black white-text"


.parallax-container
  .parallax
    =image_tag(@company.cover.url(:large), :alt => "Portada")
%footer.page-footer.white.darken-2
  .container
    .row.center-xs
      .col.s12.black-text.section.scrollspy#social
        =@company.name
      
      -unless @company.facebook == nil or @company.facebook == "" or @company.facebook == " " 
        .col.l3.m4.s12.center
          =image_tag("002-facebook", height: 24)
          =link_to("Facebook", @company.facebook, :target=> "_blank")
      -unless @company.email == nil or @company.email == "" or @company.email == " "  
        .col.l3.m4.s12.center
          =image_tag("7-email", height: 24)
          =link_to("Email", "mailto:#{@company.email}", :target=> "_blank")
      -unless @company.website == nil or @company.website == "" or @company.website == " "  
        .col.l3.m4.s12.center
          =image_tag("website", height: 24)
          =link_to("Sitio web", @company.website, :target=> "_blank")
      -unless @company.instagram == nil or @company.instagram == "" or @company.instagram == " "  
        .col.l3.m4.s12.center
          =image_tag("instagram", height: 24)
          =link_to("Instagram", @company.instagram, :target=> "_blank")
      -unless @company.linkedin == nil or @company.linkedin == "" or @company.linkedin == " "  
        .col.l3.m4.s12.center
          =image_tag("linkedin", height: 24)
          =link_to("LinkedIn", @company.linkedin, :target=> "_blank")
      -unless @company.phone == nil or @company.phone == "" or @company.phone == " "  
        .col.l3.m4.s12.center
          =image_tag("phone", height: 24)
          =link_to("Teléfono", @company.phone, :target=> "_blank")
      -unless @company.whatsapp == nil or @company.whatsapp == "" or @company.whatsapp == " "  
        .col.l3.m4.s12.center
          =image_tag("023-whatsapp-logo", height: 24)
          =link_to("WhatsApp", "https://api.whatsapp.com/send?phone=#{@company.whatsapp}&text=Hola%20#{@company.name}!%20Les%20escribo%20desde%20la%20web", :target=> "_blank")
      -unless @company.twitter == nil or @company.twitter == "" or @company.twitter == " "  
        .col.l3.m4.s12.center
          =image_tag("twitter", height: 24)
          =link_to("Twitter", @company.twitter, :target=> "_blank")