config/routes.rb
Rails.application.routes.draw do
  
  
  resources :profiles, as: :users, only: [:show, :update]
  
  #devise_for :users, controllers: {registrations: "registrations"}
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  #Redireccionar c a companies
  get '/c/:id', to: redirect('/companies/%{id}')
  
  resources :companies do
  	resources :cards do
      resources :transactions
    end
    #Entorno de trabajo
    get 'panel', to: 'cards#scan'
    post 'panel', to: 'cards#scan'
    get 'prueba', to: 'companies#freeTrial'
    get 'stats', to: 'companies#stats'
    get 'requestCard', to: 'companies#send_mail_card_request'
  
  end

  #Ruta para asignar usuario a tarjeta existente
  post 'asignar', to: 'cards#asignuser'
  

  #Mostrar INDEX si está logueado
  authenticated :user do
  	root 'main#index'
  end
  
  #Mostrar página de aterrizaje si no está logueado
  unauthenticated :user do
  	devise_scope :user do
  		root 'main#landing'
  	end
  end

  #Rutas dinámicas para nombres de usuario de las compañías
  #datos = Company.all
  
  #datos.each do |c|
    #A menos que el alias esté vacío...
  #  unless c.alias == nil
  #    get c.alias, to: 'companies#show', :id => c.id    
  #  end
  #end
  

end

app/views/layouts/_add_card.haml
.row.center-md
  .col-xs-12.col-sm-6.col-md-4
    .card.bordeRedondeado
      = form_tag(asignar_path, method: "post") do
        .card-title.black.white-text.center
          Añadir tarjeta
        .card-content
          = label_tag(:num, "Número de tarjeta (13 dígitos):")
          .teal.lighten-5.littleBordeRedondeado
            = text_field_tag(:num)
          = label_tag(:pin, "PIN:")
          .teal.lighten-5.littleBordeRedondeado
            = text_field_tag(:pin)
        .card-actions
          = submit_tag("Añadir", :class=>"btn teal lighten-3 waves-effect")

app/views/layouts/_facebooksdk.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{895701587303562}',
      cookie     : true,
      xfbml      : true,
      version    : '{3.0}'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_footer.haml
%footer.page-footer.black
  .container.texto-turquesa-normal
    .row
      .col.l2.s12.center
        = link_to(image_tag("0.5x/logoblanco.png", width: "60"), "https://www.praemium.com.ar")
      .col.l2.m3.s6
        %h5 Redes sociales
        %p 
          =link_to "Facebook", "https://www.facebook.com/praemium.oficial/", :target => "_blank"
        %p
          =link_to "YouTube", "https://www.youtube.com/channel/UCPN9PoYJ1FSyeWU7e6z6chQ?view_as=subscriber", :target => "_blank"
        %p 
          =link_to "LinkedIn", "https://www.linkedin.com/company/praemium-argentina/", :target => "_blank"
        %p
          =link_to(image_tag("whatsapp", height: 24), "https://api.whatsapp.com/send?phone=+5493417183662&text=Hola! Quiero obtener más información sobre los planes y servicios que ofrecen en Praemium!")
          =link_to(raw("<i class=material-icons>email</i>"), "mailto: info@praemium.com.ar")
      .col.l3.m4.s6
        %h5
          =link_to "Blog", "https://praemium.com.ar/blog", :target => "_blank"
        %p
          =link_to "Ayuda y Documentación", "https://www.praemium.com.ar/blog/index.php/docs/", :target => "_blank"
        %p
          =link_to "Hacé crecer tu comercio", "https://praemium.com.ar/blog", :target => "_blank"

      
      
      

      .col.l3.m4.s12
        %h5 Legales
        %p
          %a{:href=>'#privacidad'} Privacidad
        %p
          %a{:href=>'#term'} Términos y condiciones
        /%p
        /  %a{:href=>'#licencia'} Licencia
      .col.s12.center
        -unless user_signed_in?
          %h5 Cuenta
          %p
            %a{:href=>'\users\sign_up'} Registrarme
          %p
            %a{:href=>'\users\sign_in'} Iniciar sesión
        -else
          %h5 Soy un comerciante
          %p
            =link_to "Iniciar prueba gratis", new_company_path, :class=>"btn red"
        #privacidad.modal.modal-fixed-footer
          .modal-content
            = render 'layouts/privacidad'
          .modal-footer
            %a.modal-action.modal-close.waves-effect.btn-flat Cerrar
        #term.modal.modal-fixed-footer
          .modal-content
            = render 'layouts/terminos'
            = render 'layouts/privacidad'
          .modal-footer
            %a.modal-action.modal-close.waves-effect.btn-flat Cerrar
        #licencia.modal.modal-fixed-footer
          .modal-content
            %h4 Licencias
            %p licencias

          .modal-footer
            %a.modal-action.modal-close.waves-effect.btn-flat Cerrar
  .footer-copyright
    .container.center
      2018 Praemium. Todos los derechos reservados

app/views/layouts/_footercompanies.haml
%footer.page-footer.black
  .container.texto-turquesa-normal
    .row.center-xs
      .col.s12
        %a{:href=>'#term'} Información legal

      /%p
      /  %a{:href=>'#licencia'} Licencia
      #term.modal.modal-fixed-footer
        .modal-content
          = render 'layouts/terminos'
        .modal-footer
          %a.modal-action.modal-close.waves-effect.btn-flat Cerrar

        .modal-footer
          %a.modal-action.modal-close.waves-effect.btn-flat Cerrar
  .footer-copyright
    .container.center
      .row.middle-xs.center-xs
        = image_tag("0.5x/logoblanco.png", width: "35", alt: "Logo de Praemium: soluciones para comercios")
        .black-text ;-)
        %a.white-text{:href=>"https://www.praemium.com.ar"} Desarrollado por Praemium.

app/views/layouts/_praemium_nav.haml
-if user_signed_in?
  %nav.white
    .nav-wrapper
      .brand-logo
        =image_tag("imagoBlack", height: 50)
      .hide-on-large-only
        %a.black-text.button-collapse.sidenav-trigger{"data-activates"=>"mobile-demo", :href => "#"}
          %i.material-icons menu
      %ul.right.hide-on-med-and-down.black-text
        %li
          = link_to "Mis tarjetas", root_path, :class => "black-text"
        %li
          = link_to "Mi perfil", user_path(current_user.id), :class => "black-text"
        %li
          %a.black-text{ :href => "https://praemium.com.ar/blog", :target=> "_blank"} Blog
        %li
          = link_to "Cerrar sesión", destroy_user_session_path, method: :delete, :class => "black-text"
  %ul.side-nav#mobile-demo.grey.lighten-5
    %li.center
      =image_tag("logoh", :class => "logoCompany")
    %li
      = link_to raw("<i class='material-icons'>credit_card</i>Mis tarjetas"), root_path, :class => "black-text"
    %li
      = link_to raw("<i class='material-icons'>account_circle</i>Mi perfil"), user_path(current_user.id), :class => "black-text"
    %li
      %a.black-text{ :href => "https://praemium.com.ar/blog", :target=> "_blank"}
        %i.material-icons info
        Blog
    %li
      = link_to raw("<i class='material-icons'>close</i>Cerrar sesión"), destroy_user_session_path, method: :delete, :class => "black-text"

app/views/layouts/_privacidad.haml
%h1 POLÍTICA DE PRIVACIDAD
%p La adhesión del usuario en el sitio web como participante del Programa, la creación de una cuenta personal y/o la aceptación de estos Términos y Condiciones de Uso, implica que el usuario presta su consentimiento expreso, libre e informado para la inclusión, uso y tratamiento de sus datos personales por PRAEMIUM , para almacenar dichos datos en una base de datos registrada a su nombre; utilizar esos datos con fines publicitarios, promocionales y comerciales; como información de contacto; a los fines de establecer acciones de comunicación y marketing, promociones y/o beneficios comerciales y/o para enviarle información referida al Programa y/o solicitarle otra información; y efectuar el tratamiento de dichos datos, por cuenta, conforme a los objetivos del Programa, para que PRAEMIUM  le envíe boletines, newsletters o correspondencia sobre novedades institucionales, comerciales y promocionales de PRAEMIUM  o cualquier clase de información que la empresa considere de interés para los usuarios.
%p En cualquier caso que así lo desee el usuario y/o cliente puede solicitar mediante notificación por correo electrónico y/o postal que no se le envíen boletines, newsletters y/o promociones o correspondencia sobre novedades instituionales.
%p La información y datos voluntariamente proporcionados por el usuario a PRAEMIUM  a través del sitio web serán incluidos en una base de datos bajo responsabilidad de ésta y tratados bajo normas de estricta confidencialidad.
 
%p PRAEMIUM  respeta la privacidad de los usuarios y se encuentra en cumplimiento de la Ley 25326.  PRAEMIUM  realizará el tratamiento de sus datos personales en un todo de acuerdo con las disposiciones de la Ley Nº 25.326 de Protección de Datos Personales, Decreto Reglamentario Nº 1558/2001 y demás normativa vigente, adoptando los recaudos técnicos y organizativos necesarios en lo que respecta a la custodia, almacenamiento, conservación y confidencialidad de la información con el fin de evitar su alteración, pérdida, tratamiento o acceso no autorizado.
%p Los datos del cliente serán ingresados manualmente por él mismo, u obtenidos de Facebook o G+ con su previa autorización.
%p Los usuarios podrán solicitar a PRAEMIUM  el acceso, actualización, rectificación, supresión y/o sometimiento a confidencialidad de la información personal de la que son titulares incluida en la base de datos, para lo cual deberán enviar un email a privacidad@praemium.com.ar.
%p El usuario que solicitare la supresión de su información personal de la base de datos, será dado de baja del sitio web y del Programa PRAEMIUM  conforme lo previsto en los presentes términos y condiciones. Sin perjuicio de lo aquí establecido, los usuarios podrán actualizar y/o rectificar sus datos personales incluidos en la base de datos de PRAEMIUM   accediendo a su cuenta personal a través del sitio web, mediante el uso de su clave de acceso personal e intransferible. Tanto los clientes, usuarios y/o los administradores de comercios, deberán aceptar estos términos y condiciones para comenzar a operar en PRAEMIUM.
%p PRAEMIUM  no se hace responsable de la exactitud, utilidad o disponibilidad de cualquier información que se transmita o ponga a disposición a través del sitio, y no será responsable
por cualquier error u omisión en dicha información.
 
%h2 ¿Qué datos se recolectan?
%p PRAEMIUM  recolecta datos relativos a la identidad de los clientes y de su localización. Los administradores de comercios pueden solicitar a los clientes información adicional para ofrecerles un mejor servicio, y aceptan hacerse cargo de mantener la privacidad de esta información, según la normativa vigente,  no pudiendo compartirla, cederla ni trasmitirla a terceros fuera o no participantes del presente programa.
 
%h2 ¿Por qué se recolectan datos personales? ¿Quién tiene acceso a la misma?
%p PRAEMIUM  recolecta información que luego utilizará de forma anónima para ofrecer mejoras en los productos y servicios.
%p A su vez, los datos personales de los clientes, son exhibidos a los administradores de comercios, a los que el cliente esté adherido, si aquellos así lo requieren, para que el comerciante pueda brindarle atención personalizada (llamarlo por su nombre, enviarle productos a su domicilio, enviarle saludos por su cumpleaños).
%p Exceptuando a los administradores de comercios, o requerimientos especiales por ley, no se
exhibe la información de los clientes a terceros. En ningún caso se utilizamos los datos obtenidos para finalidades distintas de aquéllas para las que se solicitan.
 
%h2 ¿Dónde se almacena la información?
%p PRAEMIUM  trabaja con servidores que replican la información varias veces y en distintos nodos para que esté siempre disponible en caso de incidentes, cumpliendo además con altos
estándares de seguridad. Toda la información que se intercambia entre los usuarios y los servidores está cifrada, por lo que está protegida en caso de que sea robada por un intermediario.
 
%h2 ¿Cuánto tiempo se guarda la información?
%p Los datos personales de los clientes se guardan hasta que éste elimine su cuenta. Los datos adicionales de clientes que hayan sido solicitados por algún comerciante, serán eliminados cuando el cliente lo desee o cuando sea dado de baja en el comercio que haya pedido los datos, o bien cuando el comerciante solicite su eliminación. Los datos de los comercios adheridos serán guardados en la base de datos de PRAEMIUM  aunque el comerciante haya dado de baja el servicio, para facilitar futuras altas en el sistema, y serán eliminados si el comerciante lo solicita explícitamente para lo cual deberán enviar un email privacidad@praemium.com.ar.
 
%h2 Acceso restringido
%p Toda la información disponible en PRAEMIUM  es de acceso restringido a usuarios.
%p Cada usuario dispone de información que le permite acceder a diferentes zonas restringidas, y es responsabilidad del usuario asegurarse de mantener la confidencialidad de las claves que le permiten acceder a estas zonas restringidas.
 
%h2 COOKIES
%p El sitio web utiliza una tecnología de persistencia de información denominada “cookies” consistente en archivos que se almacenan automáticamente en el dispositivo del usuario conteniendo información que se intercambia vía internet entre el navegador y la aplicación web para facilitar y acelerar la navegación y los ulteriores accesos al sitio, o con fines estadísticos y de análisis de carácter general. En ningún caso los archivos -cookies- pueden leer información del dispositivo del usuario o archivos creados por otros sitios ni permitirán la identificación de una persona concreta. El usuario puede impedir el uso de cookies ya que éste es facultativo. En ese caso PRAEMIUM  no garantiza el correcto funcionamiento de los contenidos, servicios y funcionalidades del sitio web.
 
%h2 MARCO LEGAL
%p Marco Legal: Ley Nº 25.326 de Protección de Datos Personales y sus modificatorias; Decreto Reglamentario Nº 1558/01; Disposiciones de la Dirección Nacional de Protección de Datos Personales y demás normativa vigente en la materia.
%p "El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326". (Disposición N° 10/2008 de la Dirección Nacional de Protección de Datos Personales, Artículo 1°).
%p Toda persona tiene derecho a que sean rectificados, actualizados y, cuando corresponda, suprimidos o sometidos a confidencialidad los datos personales de los que sea titular, que estén incluidos en un banco de datos. (Artículo 16, Ley Nº 25.326). La rectificación, actualización o supresión de datos personales inexactos o incompletos que obren en registros públicos o privados se efectuará sin cargo alguno para el interesado. (Artículo 19, Ley Nº 25.326).“(Archivos, registros o bancos de datos con fines de publicidad). 1. En la recopilación de domicilios, reparto de documentos, publicidad o venta directa y otras actividades análogas, se podrán tratar datos que sean aptos para establecer perfiles determinados con fines promocionales, comerciales o publicitarios; o permitan establecer hábitos de consumo, cuando éstos figuren en documentos accesibles al público o hayan sido facilitados por los propios titulares u obtenidos con su consentimiento.2. En los supuestos contemplados en el presente artículo, el titular de los datos podrá ejercer el derecho de acceso sin cargo alguno.3. El titular podrá en cualquier momento solicitar el retiro o bloqueo de su nombre de los bancos de datos a los que se refiere el presente artículo.”. (Artículo 27, Ley Nº 25.326). “…El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326.” (Disposición Nº 10/2008 de la Dirección Nacional de Protección de Datos Personales, Artículo 1º).
%p "La DIRECCION NACIONAL DE PROTECCION DE DATOS PERSONALES, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales". (Disposición N° 10/2008 de la Dirección Nacional de Protección de Datos Personales, Artículo 2°).
%p Para contactar con la Dirección Nacional de Protección de Datos Personales podrá dirigirse a Sarmiento Nº 1118, piso 5º de la Ciudad Autónoma de Buenos Aires (C1041AAX); vía internet en el sitio web www.jus.gov.ar/datos-personales.aspx; o por correo electrónico a infodnpdp@jus.gov.ar.
 
%h2 ALCANCE
%p El no ejercer un derecho por parte de PRAEMIUM o la falta de exigencia de cumplimiento de
cualquiera de estos términos y condiciones, no podrá ser interpretado como renuncia al ejercicio o a la exigencia de cumplimiento de aquéllos. La renuncia a cualquiera de los términos y condiciones del presente no se interpretará como una renuncia continua. La finalización o suspensión de acceso al sitio web por parte del usuario, como cualquier acción o inacción de su parte, no harán finalizar la vigencia de estos términos y condiciones, los que mantendrán plena vigencia, sujeta esta última sólo a cualquier modificación que de los mismos efectuare PRAEMIUM.
Se deja constancia que a todos los efectos legales, PRAEMIUM tiene constituido su domicilio en Av. del Trabajo 224, Villa Constitución, Santa Fe, República Argentina, donde serán válidas todas las notificaciones y/o requerimientos judiciales y/o extrajudiciales.
 
%h2 LEY APLICABLE. JURISDICCION.
%p Estos términos y condiciones regirán y se interpretarán de acuerdo con las leyes de la República  Argentina, sea que el sitio web sea accedido desde esta última o desde el extranjero. El usuario acuerda que cualquier controversia que pudiera suscitarse con motivo del uso y/o acceso al sitio  web, sus contenidos, servicios y/o funcionalidades, entre otros; de la interpretación, aplicación,  ejecución y/o extinción de estos términos y condiciones, será sometida a la jurisdicción de los Tribunales Ordinarios de la ciudad de Rosario, renunciando expresamente a cualquier otro fuero y/o jurisdicción que pudiere corresponderle. 
 
%p
  %b La utilización e ingreso a este sitio web de PRAEMIUM implica el conocimiento y  aceptación por parte del usuario de sus Términos y Condiciones de Uso y Política de privacidad.

app/views/layouts/_sidenav.haml
-if user_signed_in?
	.fixed-action-btn
		%a.btn-floating.btn-large.waves.waves-effect.turquesa
			%i.material-icons menu
		%ul
			%li
				= link_to raw("<i class='material-icons'>credit_card</i> Perfil"), root_path, :class => "btn-floating green"
				.texto-negro.textoSombreado Praemium
			%li
				%a.btn-floating.red.lighten-3.modal-trigger{:href => "#addCard"}
					%i.material-icons add
				.black-text.textoSombreado Agregar
			%li
				= link_to raw("<i class='material-icons'>account_circle</i> Perfil"), user_path(current_user.id), :class => "btn-floating blue"
				.black-text.textoSombreado Mi Perfil
			
			%li
				= link_to raw("<i class='material-icons'>close</i> Perfil"), destroy_user_session_path, method: :delete, :class => "btn-floating red"
				.black-text.textoSombreado Cerrar
#addCard.modal
	.modal-content
		.row
			.col.s12.right
				.btn.right.modal-close.btn-flat
					%i.material-icons close
		.row
			.col.s12
				=render partial: "layouts/add_card"
		

app/views/layouts/_sidenav.html.erb
<% if user_signed_in? %>

  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    <li>
    	<%= link_to raw("<i class='material-icons'>insert_chart</i> Inicio"), root_path  %>
    </li>
    <li>
    	<%= link_to raw("<i class='material-icons'>insert_chart</i> Perfil"), user_path(current_user.id)  %>
    </li>
    <li class="divider"></li>
    <li>
    	<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
    </li>
  </ul>


  <% if current_user.is_owner? %>
  	<% unless @company==nil %><% unless @company.id==nil %>
	  <div class="fixed-action-btn horizontal" style="bottom: 45px; right: 24px;">
	    <a class="btn-floating btn-large red tooltipped" data-position="top" data-tooltip="Menú de empresa" href=<%= company_path(@company) %>>
	      <i class="large mdi-navigation-menu material-icons"> apps</i>
	    </a>
	    <ul>
	      <li><a href=<%= company_panel_path(@company) %> class="btn-floating red tooltipped" data-position="top" data-tooltip="Entorno de trabajo">
	      	<i class="material-icons">touch_app</i>
	      </a></li>
	      <li><a href=<%= new_company_card_path(@company) %> data-position="top" data-tooltip="Crear tarjetas" class="btn-floating yellow darken-1 tooltipped">
	      	<i class="material-icons">credit_card</i>
	      </a></li>

	      <li><a href=<%= company_cards_path(@company) %> data-position="top" data-tooltip="Clientes" class="btn-floating green tooltipped">
	      	<i class="material-icons">people</i>
	      </a></li>

	      <li><a href="#" data-position="top" data-tooltip="Estadísticas" class="btn-floating blue tooltipped">
	      	<i class="material-icons">timeline</i>
	      </a></li>


	    </ul>
	  </div>

	<% end %><% end %><% end %>


<% end %>

app/views/layouts/_sidenav_not.html.erb
    -if user_signed_in?
      %nav

        .nav-wrapper.white.littlePadding
          .brand-logo.center
            
            =link_to image_tag("logoh.png", :width => 200), root_path

          %ul.black-text#nav-mobile
            %a.black-text.dropdown-button{:href=>'#', "data-activates"=>'dropdown1'}
              %i.material-icons menu
            
          /
          /  -else
          /    %ul.right.hide-on-med-and-down
          /      %li
          /        =link_to "Iniciar sesión", new_user_session_path

<% if user_signed_in? %>

  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    <li>
    	<%= link_to raw("<i class='material-icons'>insert_chart</i> Inicio"), root_path  %>
    </li>
    <li>
    	<%= link_to raw("<i class='material-icons'>insert_chart</i> Perfil"), user_path(current_user.id)  %>
    </li>
    <li class="divider"></li>
    <li>
    	<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
    </li>
  </ul>


  <% if current_user.is_owner? %>
  	<% unless @company==nil %><% unless @company.id==nil %>
	  <div class="fixed-action-btn horizontal" style="bottom: 45px; right: 24px;">
	    <a class="btn-floating btn-large red tooltipped" data-position="top" data-tooltip="Menú de empresa" href=<%= company_path(@company) %>>
	      <i class="large mdi-navigation-menu material-icons"> apps</i>
	    </a>
	    <ul>
	      <li><a href=<%= company_panel_path(@company) %> class="btn-floating red tooltipped" data-position="top" data-tooltip="Entorno de trabajo">
	      	<i class="material-icons">touch_app</i>
	      </a></li>
	      <li><a href=<%= new_company_card_path(@company) %> data-position="top" data-tooltip="Crear tarjetas" class="btn-floating yellow darken-1 tooltipped">
	      	<i class="material-icons">credit_card</i>
	      </a></li>

	      <li><a href=<%= company_cards_path(@company) %> data-position="top" data-tooltip="Clientes" class="btn-floating green tooltipped">
	      	<i class="material-icons">people</i>
	      </a></li>

	      <li><a href="#" data-position="top" data-tooltip="Estadísticas" class="btn-floating blue tooltipped">
	      	<i class="material-icons">timeline</i>
	      </a></li>


	    </ul>
	  </div>

	<% end %><% end %><% end %>


<% end %>

app/views/layouts/_signup_component.haml
.col.s12.m8.l4.bordeRedondeadoChiquito.black
  %ul#tabs.tabs.black
    %li.tab.col.s6
      %a.white-text{href: "#tarjeta"} Tengo una tarjeta
    %li.tab.col.s6.azul
      %a.white-text{href: "#comercio"} Tengo un comercio
  = form_for(:user, :url => registration_path(:user)) do |f|
    #tarjeta.col.s12
      %h2.center Registrá tu tarjeta
      .input-field.col.s12
        %h6.white-text Correo electrónico
        /%input#email.validate.grey.lighten-5{:type => "email"}
        = f.email_field :email, autocomplete: "email", :class=>"validate grey lighten-5"
        /%label{:for=>"email", "data-error"=>"Mail incorrecto"}
        /  Correo electrónico
      .input-field.col.s12
        %h6.white-text Contraseña
        = f.password_field :password, autocomplete: "off", :class=>"validate grey lighten-5"
        /%input#password.validate.grey.lighten-5{:type => "password"}
        /%label{:for=>"password"}
        /  Contraseña
      .input-field.col.s12
        %h6.white-text Confirmar contraseña
        = f.password_field :password_confirmation, autocomplete: "off", :class=>"validate grey lighten-5"
        /%input#confirmPassword.validate.grey.lighten-5{:type => "password"}
        /%label{:for=>"confirmPassword"}
        /  Confirmar contraseña
      .col.s12.center
        = flash[:alert]
        = recaptcha_tags
        = hidden_field_tag :redirect_to, params[:redirect_to]
      .col.s12.center
        = f.submit "Registrarme!", :class => "btn turquesa white-text"
        /%a.white-text Registrarme!
      .col.s12.center
        %p.white-text O bien
      .col.s12.center.btn.azulFb
        = link_to "Iniciar con Facebook", user_facebook_omniauth_authorize_path, class: "white-text"  
      .col.s12.center
        %p Lol
  = form_for(:user, :url => registration_path(:user)) do |g|
    #comercio.col.s12.azul
      %h2.center.white-text Registrá tu comercio
      .input-field.col.s12
        %h6.white-text Correo electrónico
        /%input#email.validate.grey.lighten-5{:type => "email"}
        = g.email_field :email, autocomplete: "email", :class=>"validate grey lighten-5"
        /%label{:for=>"email", "data-error"=>"Mail incorrecto"}
        /  Correo electrónico
      .input-field.col.s12
        %h6.white-text Contraseña
        = g.password_field :password, autocomplete: "off", :class=>"validate grey lighten-5"
        /%input#password.validate.grey.lighten-5{:type => "password"}
        /%label{:for=>"password"}
        /  Contraseña
      .input-field.col.s12
        %h6.white-text Confirmar contraseña
        = g.password_field :password_confirmation, autocomplete: "off", :class=>"validate grey lighten-5"
        /%input#confirmPassword.validate.grey.lighten-5{:type => "password"}
        /%label{:for=>"confirmPassword"}
        /  Confirmar contraseña
      .col.s12.center
        = flash[:alert]
        = recaptcha_tags
        = hidden_field_tag :redirect_to, params[:redirect_to]
      .col.s12.center
        = g.submit "Registrarme!", :class => "btn turquesa white-text"
        /%a.white-text Registrarme!
      .col.s12.center
        %p.white-text O bien
      .col.s12.center.btn.azulFb
        = link_to "Iniciar con Facebook", user_facebook_omniauth_authorize_path, class: "white-text"  
      .col.s12.center.texto-azul
        %p *.*